### ISSUE TITLE
CI and setup fixes

### ISSUE THREAD

**Issue by pretorh** [pretorh/yt-queue#5]
- [x] publish only when lint and (normal) tests also pass: #6 
- [x] use dynamic version number #7 #8 
- [x] check linting of files #9
